### ISSUE TITLE
Epic 1: Have a basic API up and running

### ISSUE THREAD

**Issue by mdisumma** [SchoolOfCode/bc17-w4d2-project-jjm#1]
### Description:

As Klara, a Full Stack Engineer at TrackIt I want to be able to use a framework so I can focus on building code that actually delivers the features I need to build.

As John, a project manager at TrackIt I want our engineers to use modern frameworks that that they can ship features quickly and safely.

### Acceptance Criteria:

Given I am a new developer joining the team,
When I clone down the backend repo,
Then I should see a clear README that details how to install and run the application using Node through a command line. The application is an Express API.

Given I am a developer who has just followed the instructions to run and install the application (our Express APP),
When I make a GET request to “http://localhost:3000/”,
Then I should get back a response with status code of 200 and text saying “Hello World!”
Then I should also see that the Node API has also logged the request in the terminal (console.log)

### Description:

As Kenny, a busy front end engineer I need to be able to send a POST request with a JSON request body (new activity) to the API so that I can make a simple form that allows my user to submit new activity.

As Norman, a Tech Lead working across lots of projects I need to be able to depend on conventions like: the response object always containing a key called data or error, or the status code being an accurate indication of the success/failure (and reason) of the request.

### Acceptance Criteria:

Given I am a developer who has the Activity API running,
When I make a POST request to “http://localhost:3000/activities” with a request body containing a JSON object (new activity),
Then the API should save the new activity to the activities.json file giving it a unique “id” (UUID) and activity_submitted (time stamp - Date.now()),
Then the the request should succeed, responding with the correct status code and the activity object that I posted as the response body (response.data).

Given I am a developer who has made an invalid POST request by missing a required request body field like, activity_type or activity_duration,
When I inspect the API response,
Then the request should fail, responding with the correct status code and a clear error message (response.error).
```[tasklist]
### Tasks
- [x] create A node project using npm init
- [x] Install express in the dependencies
- [x] create endpoints for get
- [x] create endpoints for post
- [x] create a activities.json file to store activities using time stamp - Date.now()
- [x] if the request is responding with the correct status should return the response.data
- [x] if the request request fail,should responding with the correct status code and a clear error message (response.error).
```

**Comment by mdisumma** [comment]
create a file
